### ISSUE TITLE
Not exciting

### ISSUE THREAD

**Issue by zarazan** [dalexj/lunch_time#3]
There should be some kind of exciting spinner, or countdown, maybe some fireworks.

**Comment by dalexj** [comment]
ok

**Comment by Ameobea** [comment]
More CSS please @dalexj

**Comment by Ameobea** [comment]
My code monkey services are available for the low rate of $35/hour you know how to reach me

**Comment by dalexj** [comment]
go to school

**Comment by zarazan** [comment]
Get back to work

**Comment by Ameobea** [comment]
Fixed in #4
